- name: copying the {{COMPONENT}} repo
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install {{ COMPONENT }}
  ansible.builtin.package:
    name: redis-6.2.7
    state: present

- name : updating the listner address conf
  replace: 
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name : updating the listner address conf
  replace: 
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'


- name: Enable & Restart service {{COMPONENT}}
  ansible.builtin.service:
    name: redis
    state: started 
    enabled: yes 

