- name: copying the mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name : updating the listner address conf
  replace: 
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Enable & Restart service mongod
  ansible.builtin.service:
    name: mongod
    state: started  #DB should not restart it will impact the Application
    enabled: yes 

- name: Disable auto shutdown and set hostname
  shell: set Disable-auto-shutdown && set-hostname {{ COMPONENT }}

- name: Downlaod and extract
  ansible.builtin.include_role: # inclusing another role to use the task in another role
    name: common #specifying another role name
    tasks_from: downlaod #specfying the name of task file main.yml /download.yml

- name: Injecting the catalogue schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users