#First stating play, which start with list(-)
- name: play1
#lets specify the inventory to the play (egs: non+prod/Server12/test or all)
  hosts: non_prod
  tasks:
    - name: print hello word message in play1 - task1
      ansible.builtin.debug:
        msg: Hi!! Preethi, This is your first Ansible playbook code

    - name: print hello word message in  play1 - task2
      ansible.builtin.debug:
        msg: Hi!! Preethi, This is your first Ansible playbook code

#Can have another playbook as well

- name: play2
  hosts: non_prod
  tasks:
    - name: print hello word message in Play2- task1
      ansible.builtin.debug:
        msg: Hi!! Preethi, This is your first Ansible playbook code

    - name: print hello word message in Play2- task2
      ansible.builtin.debug:
        msg: Hi!! Preethi, This is your first Ansible playbook code