#First stating play, which start with list(-)
- name: play1
#lets specify the inventory to the play (egs: non+prod/Server12/test or all)
  hosts: non_prod
  tasks:
    - name: print hello word message in Play1
      ansible.builtin.debug:
        msg: Hi!! Preethi, This is your first Ansible playbook code

    - name: print hello word message in Play2
      ansible.builtin.debug:
        msg: Hi!! Preethi, This is your first Ansible playbook code