- name: sample example on variable
  hosts: non_prod
  vars:
    URL: dev.google.com #This are global variables
  tasks:
    - name: Printing URL
      ansible.builtin.debug:
        msg: printing the {{ URL }}

    - name: Printing URL
      ansible.builtin.debug:
        msg: printing the {{ URL }}
      vars:
        URL: localvariable.checking.com