- name: sample example on variable
  hosts: non_prod
  vars:
    URL: dev.google.com #This are global variables
  tasks:
    - name: Printing URL
      ansible.builtin.debug:
        msg: printing the {{ URL }}

    - name: Printing URL
      ansible.builtin.debug:
        msg: printing the {{ cli_url }}
      vars:
        url: localvariable.checking.com #This is local variable declaration

    - name: Printing URL
      ansible.builtin.debug:
        msg: printing the {{ cli_url }} # declaring the variable value at CLI end 

#In CLI command "-e varible=value" syntax. 
#-e is expession we use for any values we declare most everwhere we use like this -e to declare
#ansible-playbook -i inventory -u centos -e ansible_password=DevOps321 -e cli_url=cliurl.command.com CLI_Variable.yml

  