#when condition: if condition staisfed the excute else exit the loop

- name: sample example on conditions
  hosts: non_prod
  vars:
    action: true
    sample: xyz
  tasks:
    - name: Only for centos machines checking
      debug:
        msg: Hello centos!!
      when: ansible_distribution == "CentOS"

    - name: Only for unbuntu machines checking
      debug:
        msg: Hello Ubuntu!!
      when: ansible_distribution == "Ubuntu"

    - name: defined the action is true
      debug:
        msg: now only print when action is true
      when: action
    
    - name: defined the defined and undefined keywords
      debug:
        msg: "sample is defined and declared then only run "
      when: sample is defined  #excute only when smaple is defined 

     - name: defined the defined and undefined keywords
      debug:
        msg: "sample_un is defined and declared then only run "
      when: sample_un is defined  #won't excute as sample_un is undefined 


    

#can do other examples restart, stop all the centos machines only

#Boolen condition : 

#"defined and undfined are pre-defined keywword"

    
