
- name: sample example on copy
  hosts: lab
  tasks:
    - name: example on copy
      copy:
        src: copy_testfile.conf
        dest: /tmp/fold1/test.conf

#if destination path "/tmp/fold1/test.conf" with new name it will "test.conf" overwrittes.
#if only provided the path "/tmp/fold1/" -- it copies.

#"Ansible is very smart it will only task action is any changes done"
#Else it doesn't change even if we copy again again ---very smart