
- name: sample example on loop
  hosts: dev
  tasks:
    - name: Running the dev envirnment
      debug:
        msg: value is {{ item }}
          -10
          -120
          -30
          -40

#Each and every value is refered as a "item" in loop