
- name: sample example on loop
  hosts: dev
  tasks:
    - name: example on loop
      debug:
        msg: "value is {{ item }}"
      loop:
          -10
          -120
          -30
          -40
          -abc

#Each and every value is refered as a "item" in loop