- name: sample example1
  hosts: dev
  become: yes #It means "sudo su -" as root all the task will be excuted
  tasks:
    - name: Printing id command
      shell: id
      register: OUT
    
    - name: Printing id command
      debug:
        msg: "{{ OUT }}"

- name: sample example2
  hosts: lab
  tasks:
    - name: Printing id command
      shell: id
      register: OUT
      become: yes   #only this task will be excuted as root
      
    - name: Printing id command
      debug:
        msg: "{{ OUT }}"
      

    - name: Printing id command
      shell: id
      register: OUT
    
    - name: Printing id command
      debug:
        msg: "{{ OUT }}"