- name: sample example on variable
  hosts: non_prod
  vars:
    URL: dev.google.com #This are global variables
  vars_prompt:
    name: Prompting the varibale  #declaring the variable name -not just text message
    prompt: Enter P_URL
    private: no

  tasks:
    - name: Printing URL
      ansible.builtin.debug:
        msg: printing the {{ P_URL }}

    - name: Printing URL
      ansible.builtin.debug:
        msg: printing the {{ url }}
      vars:
        url: localvariable.checking.com #This is local variable declaration

    - name: Printing URL
      ansible.builtin.debug:
        msg: printing the {{ cli_url }}

      
