
- name: sample example on tags
  hosts: non_prod
  tasks:
    - name: Running the dev envirnment
      debug:
        msg: It is dev environment
      tags: dev

    - name: Running the lab envirnment
      debug:
        msg: It is lab environment
      tags: lab

    - name: Running the ppe envirnment
      debug:
        msg: It is ppe environment
      tags: ppe

  #tags been used for the tasks, so that we can call only the required tag ans only that task will be excuted
  # -t tagname ---> we use so that only that tag task will be excuted.
  # -->$ansible-playbook -i inventory -u centos -e ansible_password=DevOps321 tags_sample.yml -t dev
