- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present
      
- name: Download and extract
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes #we use "yes" if src is not in local repository

- name: cleaning up files
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: COpy & move files 
  copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html
    remote_src: yes



# mv frontend-main/* .
# mv static/* .
# rm -rf frontend-main README.md
# mv localhost.conf /etc/nginx/default.d/roboshop.conf
