- name: copying the {{COMPONENT}} repo 
  ansible.builtin.copy:
     src: mysql.repo 
     dest: /etc/yum.repos.d/mysql.repo 
 
- name: Installing {{COMPONENT}} 
  ansible.builtin.package:
    name: 
       - mysql-community-server
       - MySQL-python
    state: present 

- name: Enable & Restart service {{COMPONENT}}
  ansible.builtin.service:
    name: mysqld
    state: started  #DB should not restart it will impact the Application
    enabled: yes 

- name: checking Mysql connection
  ansible.builtin.mysql_info:
    login_user: root
