- name: copying the {{COMPONENT}} repo 
  ansible.builtin.copy:
     src: mysql.repo 
     dest: /etc/yum.repos.d/mysql.repo 
 
- name: Installing {{COMPONENT}} 
  ansible.builtin.package:
    name: 
       - mysql-community-server
       - MySQL-python
    state: present 

- name: Enable & Restart service {{COMPONENT}}
  ansible.builtin.service:
    name: mysqld
    state: started  #DB should not restart it will impact the Application
    enabled: yes 

- name: Check the DB Password 
  community.mysql.mysql_info:
    login_user: root 
    login_password: RoboShop@1**
  ignore_errors: yes
  register: mysql_stat 

  # new fix, ensure you also install PyMySQL
- name: Installing PyMySQL
  ansible.builtin.pip:   #Pythong 2 
    name: PyMySQL
  executable: pip3  #Installation with pip3

- name: Reset the password
  when: mysql_stat.failed
  block:
    - name: Resetting the DB Passwprd
      ansible.builtin.shell: grep "temporary password" /var/log/mysqld.log | awk '{print $NF}'
      register: DEFAULT_ROOT_PASSWORD    

    - name: copying passwd change cmd to tmp file 
      ansible.builtin.copy:
        src: rootpass.sql
        dest: /tmp/rootpass.sql

    - name: changing the password
      ansible.builtin.shell: mysql  --connect-expired-password -uroot -p"{{DEFAULT_ROOT_PASSWORD.stdout}}"  < /tmp/rootpass.sql
  
- name: Check validate password plugin is removed or not 
  ansible.builtin.shell: echo show plugins | mysql -uroot -pRoboShop@1** | grep validate_password
  register: plug_info
  ignore_errors: yes 

- name: Uninstall Password Validate Plugin  
  when: plug_info.rc == 0 
  block:
    - name: Copy the SQL Password to tmp file 
      ansible.builtin.copy:
        src: plugin_unistall_cmd_validation.sql
        dest: /tmp/password-validate.sql 
        
    - name: Uninstall the plugin 
      ansible.builtin.shell: mysql  --connect-expired-password -uroot -pRoboShop@1** < /tmp/password-validate.sql 


- name: Download and extracting {{COMPONENT}} Schema
  ansible.builtin.include_role:
    name: common 
    tasks_from: download 

- name: Load Schema 
  community.mysql.mysql_db:
    state: import
    name: all
    login_user: root 
    login_password: RoboShop@1**
    target: /tmp/mysql-main/shipping.sql 

- name: Set-hostname 
  ansible.builtin.include_role:
    name: common 
    tasks_from: set-hostname 