- name: Configuring the {{COMPONENT}} repository
  ansible.builtin.copy:
    src: "{{COMPONENT}}.repo"
    dest: /etc/yum.repos.d/{{COMPONENT}}.repo

- name: Install mongodb
  ansible.builtin.package:
    name: 
      - mysql-community-server
    state: present

- name: Enable & Restart service {{COMPONENT}}
  ansible.builtin.service:
    name: mongod
    state: started  #DB should not restart it will impact the Application
    enabled: yes 

- name: checking Mysql connection
  mysql_info:
    login_user: root
