- name: Configuring the Repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing {{ COMPONENT }}
  ansible.builtin.package: 
    name: 
      - nodejs
      - gcc-c++

- name: creating the app user {{ APPUSER }}
  ansible.builtin.user:
    name: "{{ APPUSER }}"

- name: Downlaod and extract
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Installing "{{ COMPONENT }}""
  ansible.builtin.package: 
    name: npm
  state: present