- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: 
      - python36
      - gcc-c++  
      - python3-devel
    state: present 

- name: creating the app user {{ APPUSER }}
  ansible.builtin.user:
    name: "{{ APPUSER }}"
  register: APPUSER_REGISTER

- name: Download and extracting {{COMPONENT}}
  ansible.builtin.include_role:
    name: common 
    tasks_from: download 

- name: Cleanup of {{COMPONENT}} and sorting the permissions
  ansible.builtin.include_role:
    name: common
    tasks_from: cleanup

- name: Install Python Dependencies 
  ansible.builtin.pip:
    requirements: /home/{{APPUSER}}/{{COMPONENT}}/requirements.txt
    executable: pip3

- name: Update uid in APP Config 
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^uid'
    line: uid = {{APPUSER_REGISTER.uid}}

- name: Update gid in APP Config 
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^gid'
    line: gid = {{APPUSER_REGISTER.group}}


- name: Configuring and Starting {{COMPONENT}}
  ansible.builtin.include_role:
    name: common 
    tasks_from: systemd 

- name: Set-hostname 
  ansible.builtin.include_role:
    name: common 
    tasks_from: set-hostname

